DrakeTest/DrakeTest.WebUI/Controllers/PatientRecordsController.cs
using DrakeTest.Core.Contracts;
using DrakeTest.Core.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DrakeTest.WebUI.Controllers
{
    [Authorize]
    public class PatientRecordsController : Controller
    {
       
        IRepository<Patient> patient;
        IRepository<PatientRecords> patientrecords;
        public PatientRecordsController(IRepository<Patient> Patient, IRepository<PatientRecords> PatientRecords)
        {
            patient = Patient;
            patientrecords = PatientRecords;
        }
        // GET: PatientRecords
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            List<PatientRecords> patientRecords = patientrecords.Collection().Where(p => p.UserId == userId).OrderBy(c => c.CreatedAt).ToList();
            return View(patientRecords);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(PatientRecords patientRecords)
        {
            if (!ModelState.IsValid)
            {
                return View(patientRecords);
            }
            else
            {
                PatientRecords patientRecords_temp = new PatientRecords()
                {
                    UserId = User.Identity.GetUserId(),
                    height = patientRecords.height,
                    weight = patientRecords.weight,
                    test = patientRecords.test
                };

                patientrecords.Insert(patientRecords_temp);
                patientrecords.Commit();
                return RedirectToAction("Index");
            }

        }

        public ActionResult Edit(string Id)
        {
            PatientRecords patientRecordsToEdit = patientrecords.Find(Id);
            if (patientRecordsToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                
              
                return View(patientRecordsToEdit);
            }
        }
        [HttpPost]
        public ActionResult Edit(PatientRecords patientRecords, string Id)
        {
            PatientRecords patientRecordsToEdit = patientrecords.Find(Id);

            if (patientRecordsToEdit == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    return View(patientRecordsToEdit);
                }

                patientRecordsToEdit.height = patientRecords.height;
                patientRecordsToEdit.weight = patientRecords.weight;

                patientRecordsToEdit.test = patientRecords.test;
               

                patientrecords.Commit();
                return RedirectToAction("Index");
            }
        }
       
        
        public ActionResult Delete(string Id)
        {
            PatientRecords patientRecordsToDelete = patientrecords.Find(Id);
            if (patientRecordsToDelete == null)
            {
                return HttpNotFound();
            }
            else
            {
                patientrecords.Delete(Id);
                patientrecords.Commit();
                return RedirectToAction("Index");
            }
        }


    }
}

DrakeTest/DrakeTest.WebUI/Views/Shared/Info.cshtml
@{
    ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

DrakeTest/DrakeTest.WebUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
@{ 
    var username = "Account";
}
<script>
    $(document).ready(function(){
  $('[data-toggle="tooltip"]').tooltip(); 
});
  
</script>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/Pictures/FaviconLogo.png" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/sb-admin.css">
    <title>Drake</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body id="page-top">
    <!-- navbar -->
    <nav class="navbar navbar-expand-md fixed-top">


        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button" style="background-color:#004B87;">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
        <button class="btn btn-link btn-sm text-black-50 order-1 order-sm-0" id="sidebarToggle" href="#" data-toggle="tooltip" title="SideBar Toggle">
            <i class="fa fa-arrow-right"></i>
        </button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" style="margin-top:5px; border: none;background-color: transparent; float:right;">
            <i class="fa fa-bars"></i>
        </button>
        @*<a class="navbar-brand" href="@Url.Action("Index", "Home")" title="DrakeTest Logo"><div class="logo"></div></a>*@
        <a href="@Url.Action("Index", "Home")" class="navbar-brand" title="DrakeTest Logo"><img src="~/Content/Pictures/SmallLogo.png" alt="logo" style=""></a>





        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto ">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")"> <i class="fa fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-user-circle fa-fw"></i>
                        @* Check if User is Authenticated and if they are change var username to the current user's username.
                            Variable username is set to "Account" as default.*@
                        @if (Request.IsAuthenticated)
                        {
                            username = User.Identity.GetUserName();
                        }
                        @username<i class="fa fa-caret-down"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown" style="left:0;">
                        @Html.Partial("_LoginPartial")
                        <div class="dropdown-divider"></div>

                    </div>
                </li>

            </ul>
        </div>

    </nav>
    <!-- /.navbar -->

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="@Url.Action("Index", "PatientRecords")">
                    <i class="fa fa-tachometer" aria-hidden="true"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="pagesDropdown">
                    <h6 class="dropdown-header">Login Screens:</h6>
                    <a class="dropdown-item" href="login.html">Login</a>
                    <a class="dropdown-item" href="register.html">Register</a>
                    <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
                    <div class="dropdown-divider"></div>
                    <h6 class="dropdown-header">Other Pages:</h6>
                    <a class="dropdown-item" href="404.html">404 Page</a>
                    <a class="dropdown-item" href="blank.html">Blank Page</a>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index", "PatientRecords")">
                    <i class="fa fa-list" aria-hidden="true"></i>
                    <span>Records</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fa fa-fw fa-table"></i>
                    <span>Tables</span>
                </a>
            </li>

        </ul>
        <!--/. Sidebar -->





        <div id="content-wrapper">




            <div class="container-fluid">
                @RenderBody()
                <hr />
                <footer style="text-align:center;">
                    <p>&copy; @DateTime.Now.Year - DrakeTest Corporation</p>
                </footer>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/Content/js/sb-admin.min.js"></script>


</body>
</html>